// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-HSMaUpI-HYRjsrPUef8y9tBw7W4XLI',
    appId: '1:312408969872:web:3e81a7f804a36da6b0be15',
    messagingSenderId: '312408969872',
    projectId: 'pet-paradise-61cf7',
    authDomain: 'pet-paradise-61cf7.firebaseapp.com',
    storageBucket: 'pet-paradise-61cf7.appspot.com',
    measurementId: 'G-8WJ94E93J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb31mm7gS-RFj0DzEF4N9IgIf0H9DQeW8',
    appId: '1:312408969872:android:c835dec2f5b20037b0be15',
    messagingSenderId: '312408969872',
    projectId: 'pet-paradise-61cf7',
    storageBucket: 'pet-paradise-61cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FWKIjRFP5aTO6U_41kFAL3srB7W0w3w',
    appId: '1:312408969872:ios:dfa8fa4dc55e05c7b0be15',
    messagingSenderId: '312408969872',
    projectId: 'pet-paradise-61cf7',
    storageBucket: 'pet-paradise-61cf7.appspot.com',
    iosClientId: '312408969872-ph8vnr64t6qlssbisajko59hgr0a688l.apps.googleusercontent.com',
    iosBundleId: 'com.gmail.maherimran034.petparadise.petParadise',
  );
}
